[tool.black]
line-length = 119

[tool.coverage]
run.omit = ["./venv/*", "manage.py", "./apps/*/tests.py"]

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
line_length = 119
multi_line_output = 3
use_parentheses = true
skip_gitignore = true
extend_skip_glob = "apps/*/migrations/*"

[tool.djlint]
indent = 2
ignore = "H011"
